site_name: {{ cookiecutter.project_name }}

site_author: {{ cookiecutter.author_name }}

theme:
  name: "material"

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [../src]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js