name: {{ cookiecutter.package_name }}
channels:
  - conda-forge
dependencies:
  - python=3.13
  # Dataframes
  - pandas
  - pyarrow
  # Plotting
  - plotly
  - python-kaleido=0.1.0
  # Utilities
  - tqdm
  - loguru
  - ruff
  # Notebook
  - jupyter
  {% if cookiecutter.include_mkdocs %}# Docs
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-material
  - mkdocs{% endif %}
  # Other
  - pip
  - pip:
    - -e .  # Install this project as a package.

# To install: conda env create -f environment.yml
# To use: conda activate {{ cookiecutter.package_name }}
# To update: conda env update -f environment.yml --prune -n {{ cookiecutter.package_name }}